version: "3.3"

services:
  back:
    image: node:14
    ports:
      - "3000:3000"
    user: "1000:1000"
    volumes:
      - ./back:/app
    working_dir: /app
    expose:
      - 3000
    command: "npm run start:dev"
  front:
    image: node:14
    ports:
      - "3001:3001"
    expose:
      - 3001
    environment:
      - PORT=3001
    user: "1000:1000"
    volumes:
      - ./front:/app
    working_dir: /app
    command: "yarn start"
    stdin_open: true
